import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import PurpleShadow from "../images/PurpleShadow.svg";
import RightDecore from "../images/RightDecore.png";
import Plus from "../images/Plus.svg";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Jadoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" overflow-x-hidden scrollbar-hide">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden scrollbar-hide mx-auto`}
      >
        <Navbar/>
        <Image
          src={PurpleShadow}
          alt=""
          className="w-[20rem] h-[20rem]  sm:w-[16rem] sm:h-[28rem] md:w-[22rem] ms:h-[36rem] lg:w-[28rem] lg:h-[44rem] xl:w-[34rem] xl:h-[52rem] 2xl:w-[40rem] 2xl:h-[60rem] absolute -top-16 -left-20 sm:-top-32 sm:-left-16 md:-top-38 md:-left-36 lg:-top-44 lg:-left-44 xl:-top-50 xl:-left-52 2xl:-top-56 2xl:-left-60"
        />
        <Image
          src={RightDecore}
          alt=""
          className=" w-48 h-80 sm:w-[366px] sm:h-[448px] md:w-[426px] md:h-[548px] lg:w-[566px] lg:h-[673px] xl:w-[666px] xl:h-[773px] 2xl:w-[766px] 2xl:h-[873px] md:block absolute top-0 -right-0  md:-right-0 lg:-right-30 xl:-right-40"
        />
        {children}
      </body>
    </html>
  );
}
