import localFont from "next/font/local";
import "./globals.css";
import Image from "next/image";
import PurpleShadow from "../images/PurpleShadow.svg";
import RightDecore from "../images/RightDecore.svg";
import Plus from "../images/Plus.svg";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Jadoo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden scrollbar-hide`}
      >
        <Image
          src={PurpleShadow}
          alt=""
          className="w-[40rem] h-[60rem] absolute -top-56 -left-60"
        />
        <Image
          src={RightDecore}
          alt=""
          className="w-[766px] h-[873px] absolute -top-32 -right-48"
        />
        {children}
        <Image
          src={Plus}
          alt=""
          className="size-[14px] absolute top-[145.5%] right-[0.1%]"
        />
      </body>
    </html>
  );
}
